[package]
name = "cput"
version = "0.1.0"
authors = ["CPUT Protocol Contributors"]

[addresses]
cput = "0xc9007"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
